### ISSUE TITLE
Casual Meter crashing

### ISSUE THREAD

**Issue by mateustaio** [lunyx/CasualMeter#114]
Hi, i open casual meter and it work fine for the first fight but then it crash.

2016-09-15 17:56:20,203 [1] INFO  CasualMeter.App - Checking for updates.
2016-09-15 17:56:20,359 [1] INFO  CasualMeter.App - Current Version: v1.2.1.11
2016-09-15 17:56:21,076 [1] INFO  CasualMeter.App - Starting up.
2016-09-15 17:56:21,201 [14] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been enabled.
2016-09-15 17:57:31,150 [15] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Connected to server Celestial Hills.
2016-09-15 17:57:50,269 [15] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Logged in to server Celestial Hills.
2016-09-15 18:00:07,409 [15] ERROR CasualMeter.App - System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.ArraySegment`1..ctor(T[] array, Int32 offset, Int32 count)
   at NetworkSniffer.Packets.Ip4Packet.get_Payload() in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\Packets\IpPacket.cs:line 37
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpSniffer.cs:line 64
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSniffer.cs:line 16
   at NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:line 108
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 262
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDevice.cs:line 205
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 360
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread() in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:line 355
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Can you help me please?

**Comment by Gl0** [comment]
either something bad with your network card or your CPU is overloaded.

**Comment by mateustaio** [comment]
Hi, i updated my drivers and it stoped crashing for now at least, thanks.
