### ISSUE TITLE
Casual Metre crashes when I go into server (Ascension Valley)

### ISSUE THREAD

**Issue by wanttodie** [lunyx/CasualMeter#120]
Whenever I go into the server the CM crashes straight away. I tried deleting the setting file but it didn't work.
Sniffer has been enabled.
2016-07-25 17:09:17,483 [1] INFO  CasualMeter.App - Checking for updates.
2016-07-25 17:09:55,112 [1] INFO  CasualMeter.App - Current Version: v1.2.1.3
2016-07-25 17:10:03,835 [1] INFO  CasualMeter.App - Starting up.
2016-07-25 17:10:10,631 [15] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been enabled.
2016-07-25 17:17:17,773 [16] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Connected to server Ascension Valley.
2016-07-25 17:17:58,355 [16] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Logged in to server Ascension Valley.
2016-07-25 18:16:14,988 [1] ERROR CasualMeter.App - System.ArgumentNullException: Value cannot be null.
Parameter name: d
   at MS.Internal.Data.ElementObjectRef.GetObject(DependencyObject d, ObjectRefArgs args)
   at MS.Internal.Data.ObjectRef.GetDataObject(DependencyObject d, ObjectRefArgs args)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.VerifySourceReference(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2016-07-25 18:50:19,137 [16] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Logged in to server Ascension Valley.
2016-07-25 18:58:55,734 [16] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Logged in to server Ascension Valley.
2016-07-25 18:59:54,871 [1] ERROR CasualMeter.App - System.ArgumentNullException: Value cannot be null.

**Comment by lunyx** [comment]
Sorry for the delay, I was on vacation. Just released 1.2.2.0 which should resolve this as well as another bug that caused some crashes.
