### ISSUE TITLE
Casual meter not working after log in server

### ISSUE THREAD

**Issue by gary90** [lunyx/CasualMeter#134]
Could anyone help me see the log?
My casual meter are not working to show the DPS even it is conencted to the server.

2017-02-11 17:24:37,108 [1] INFO  CasualMeter.App - Checking for updates.
2017-02-11 17:24:37,389 [1] INFO  CasualMeter.App - Current Version: v1.2.3.2
2017-02-11 17:24:39,522 [6] ERROR CasualMeter.App - System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut) in C:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 614
   at Squirrel.UpdateManager.<acquireUpdateLock>b__30_0() in C:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 241
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext() in C:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CasualMeter.App.<Update>d__3.MoveNext() in D:\Workspace\visualstudio\CasualMeter\CasualMeter\App.xaml.cs:line 69
2017-02-11 17:24:39,522 [1] INFO  CasualMeter.App - Starting up.
2017-02-11 17:24:40,053 [8] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
2017-02-11 17:26:06,034 [10] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Connected to server Fey Forest.
2017-02-11 17:26:06,096 [10] ERROR CasualMeter.App - System.IO.FileNotFoundException: Could not find file 'C:\Users\user\AppData\Local\CasualMeter\app-1.2.3.2\res\opcodes\311378.txt'.
File name: 'C:\Users\user\AppData\Local\CasualMeter\app-1.2.3.2\res\opcodes\311378.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:line 37
   at Tera.Game.OpCodeNamer..ctor(String filename) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:line 23
   at CasualMeter.ShellViewModel.HandleMessageReceived(Message obj) in D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellViewModel.cs:line 404
   at Tera.Sniffing.TeraSniffer.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 80
   at Tera.Sniffing.TeraSniffer.HandleMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 152
   at Tera.Sniffing.MessageSplitter.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 53
   at Tera.Sniffing.MessageSplitter.ClientBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 41
   at Tera.PacketLog.BlockSplitter.OnBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 22
   at Tera.PacketLog.BlockSplitter.PopAllBlocks() in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 66
   at Tera.Sniffing.TeraSniffer.HandleClientToServerDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 164
   at Tera.Sniffing.ConnectionDecrypter.OnClientToServerDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 31
   at Tera.Sniffing.ConnectionDecrypter.ClientToServer(Byte[] data, Int32 needToSkip) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 107
   at Tera.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 143
   at NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 36
   at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 44
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpSniffer.cs:line 61
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSniffer.cs:line 16
   at NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:line 116
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 262
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDevice.cs:line 205
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 360
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread() in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:line 355
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2017-02-11 17:28:40,819 [1] INFO  CasualMeter.App - Checking for updates.
2017-02-11 17:28:41,101 [1] INFO  CasualMeter.App - Current Version: v1.2.3.2
2017-02-11 17:31:54,044 [17] ERROR CasualMeter.App - System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext() in C:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 528
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext() in C:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\FileDownloader.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext() in C:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.CheckForUpdates.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext() in C:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CasualMeter.App.<Update>d__3.MoveNext() in D:\Workspace\visualstudio\CasualMeter\CasualMeter\App.xaml.cs:line 69
2017-02-11 17:31:54,047 [1] INFO  CasualMeter.App - Starting up.
2017-02-11 17:31:54,405 [16] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.

**Comment by Gl0** [comment]
You have old version=> not working.
Update server is down again => meter can't update itself.

**Comment by adem940** [comment]
my meter is working well but opening too late after clicking on the shortcut, this happened since 3 days ago...

**Comment by Gl0** [comment]
Same issue - It's trying to check for updates while server is down.

**Comment by adem940** [comment]
I think lunyx has to change server provider again xD

**Comment by Gl0** [comment]
Seems he is still on old one.

**Comment by lunyx** [comment]
Yeah, that is the case.  I've been busy lately and just haven't gotten around to it.  I'm setting up the new server right now.

**Comment by lunyx** [comment]
We should be good now.

**Comment by Gl0** [comment]
btw, You should release new update for EU.

**Comment by lunyx** [comment]
Done.

**Comment by lunyx** [comment]
Done.

**Comment by adem940** [comment]
thanks bro ^^
