### ISSUE TITLE
getting unexpected error after last update (fixed)

### ISSUE THREAD

**Issue by adem940** [lunyx/CasualMeter#137]
here is the log

> 2017-03-01 01:10:08,724 [1] INFO  CasualMeter.App - Checking for updates.
2017-03-01 01:10:08,957 [1] INFO  CasualMeter.App - Current Version: v1.2.3.4
2017-03-01 01:10:11,566 [1] INFO  CasualMeter.App - Starting up.
2017-03-01 01:10:11,798 [14] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
2017-03-01 01:11:41,146 [15] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Connected to server Ascension Valley.
2017-03-01 01:11:41,199 [15] ERROR CasualMeter.App - System.IO.FileNotFoundException: Could not find file 'C:\Users\Adem\AppData\Local\CasualMeter\app-1.2.3.4\res\opcodes\311380.txt'.
File name: 'C:\Users\Adem\AppData\Local\CasualMeter\app-1.2.3.4\res\opcodes\311380.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:line 37
   at Tera.Game.OpCodeNamer..ctor(String filename) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:line 23
   at CasualMeter.ShellViewModel.HandleMessageReceived(Message obj) in D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellViewModel.cs:line 443
   at Tera.Sniffing.TeraSniffer.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 80
   at Tera.Sniffing.TeraSniffer.HandleMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 152
   at Tera.Sniffing.MessageSplitter.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 53
   at Tera.Sniffing.MessageSplitter.ClientBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 41
   at Tera.PacketLog.BlockSplitter.OnBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 22
   at Tera.PacketLog.BlockSplitter.PopAllBlocks() in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 66
   at Tera.Sniffing.TeraSniffer.HandleClientToServerDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 164
   at Tera.Sniffing.ConnectionDecrypter.OnClientToServerDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 31
   at Tera.Sniffing.ConnectionDecrypter.ClientToServer(Byte[] data, Int32 needToSkip) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 107
   at Tera.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 143
   at NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 36
   at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 44
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpSniffer.cs:line 61
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSniffer.cs:line 16
   at NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:line 116
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 262
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDevice.cs:line 205
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 360
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread() in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:line 355
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Gl0** [comment]
Wait for meter update.
As a temporary solution you can use [my fork](https://github.com/Gl0/CasualMeter/releases).

**Comment by adem940** [comment]
thank you.

**Comment by lunyx** [comment]
Fixed
