### ISSUE TITLE
An unexpected error has occured

### ISSUE THREAD

**Issue by Alexotic** [lunyx/CasualMeter#138]
Logs:
2017-03-03 16:20:16,786 [1] INFO  CasualMeter.App - Checking for updates.
2017-03-03 16:20:17,011 [1] INFO  CasualMeter.App - Current Version: v1.2.3.4
2017-03-03 16:20:17,483 [1] INFO  CasualMeter.App - Starting up.
2017-03-03 16:20:18,069 [16] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
2017-03-03 16:21:40,718 [18] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Connected to server Tempest Reach.
2017-03-03 16:21:40,817 [18] ERROR CasualMeter.App - System.IO.FileNotFoundException: Could not find file 'C:\Users\Alex\AppData\Local\CasualMeter\app-1.2.3.4\res\opcodes\311380.txt'.
File name: 'C:\Users\Alex\AppData\Local\CasualMeter\app-1.2.3.4\res\opcodes\311380.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:line 37
   at Tera.Game.OpCodeNamer..ctor(String filename) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:line 23
   at CasualMeter.ShellViewModel.HandleMessageReceived(Message obj) in D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellViewModel.cs:line 443
   at Tera.Sniffing.TeraSniffer.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 80
   at Tera.Sniffing.TeraSniffer.HandleMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 152
   at Tera.Sniffing.MessageSplitter.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 53
   at Tera.Sniffing.MessageSplitter.ClientBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 41
   at Tera.PacketLog.BlockSplitter.OnBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 22
   at Tera.PacketLog.BlockSplitter.PopAllBlocks() in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 66
   at Tera.Sniffing.TeraSniffer.HandleClientToServerDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 164
   at Tera.Sniffing.ConnectionDecrypter.OnClientToServerDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 31
   at Tera.Sniffing.ConnectionDecrypter.ClientToServer(Byte[] data, Int32 needToSkip) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 107
   at Tera.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 143
   at NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 36
   at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 44
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpSniffer.cs:line 61
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSniffer.cs:line 16
   at NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:line 116
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 262
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDevice.cs:line 205
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 360
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread() in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:line 355
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2017-03-03 16:22:24,491 [1] INFO  CasualMeter.App - Checking for updates.
2017-03-03 16:22:24,720 [1] INFO  CasualMeter.App - Current Version: v1.2.3.4
2017-03-03 16:22:25,174 [1] INFO  CasualMeter.App - Starting up.
2017-03-03 16:22:25,796 [16] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
2017-03-03 16:22:30,883 [18] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Connected to server Tempest Reach.
2017-03-03 16:22:30,930 [18] ERROR CasualMeter.App - System.IO.FileNotFoundException: Could not find file 'C:\Users\Alex\AppData\Local\CasualMeter\app-1.2.3.4\res\opcodes\311380.txt'.
File name: 'C:\Users\Alex\AppData\Local\CasualMeter\app-1.2.3.4\res\opcodes\311380.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:line 37
   at Tera.Game.OpCodeNamer..ctor(String filename) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:line 23
   at CasualMeter.ShellViewModel.HandleMessageReceived(Message obj) in D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellViewModel.cs:line 443
   at Tera.Sniffing.TeraSniffer.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 80
   at Tera.Sniffing.TeraSniffer.HandleMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 152
   at Tera.Sniffing.MessageSplitter.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 53
   at Tera.Sniffing.MessageSplitter.ClientBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 41
   at Tera.PacketLog.BlockSplitter.OnBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 22
   at Tera.PacketLog.BlockSplitter.PopAllBlocks() in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 66
   at Tera.Sniffing.TeraSniffer.HandleClientToServerDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 164
   at Tera.Sniffing.ConnectionDecrypter.OnClientToServerDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 31
   at Tera.Sniffing.ConnectionDecrypter.ClientToServer(Byte[] data, Int32 needToSkip) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 107
   at Tera.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 143
   at NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 36
   at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 44
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpSniffer.cs:line 61
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSniffer.cs:line 16
   at NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:line 116
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 262
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDevice.cs:line 205
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 360
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread() in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:line 355
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2017-03-03 16:37:23,668 [1] INFO  CasualMeter.App - Checking for updates.
2017-03-03 16:37:23,925 [1] INFO  CasualMeter.App - Current Version: v1.2.3.4
2017-03-03 16:37:24,859 [1] INFO  CasualMeter.App - Starting up.
2017-03-03 16:37:25,544 [14] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
2017-03-03 16:38:51,079 [16] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Connected to server Tempest Reach.
2017-03-03 16:38:51,144 [16] ERROR CasualMeter.App - System.IO.FileNotFoundException: Could not find file 'C:\Users\Alex\AppData\Local\CasualMeter\app-1.2.3.4\res\opcodes\311380.txt'.
File name: 'C:\Users\Alex\AppData\Local\CasualMeter\app-1.2.3.4\res\opcodes\311380.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:line 37
   at Tera.Game.OpCodeNamer..ctor(String filename) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:line 23
   at CasualMeter.ShellViewModel.HandleMessageReceived(Message obj) in D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellViewModel.cs:line 443
   at Tera.Sniffing.TeraSniffer.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 80
   at Tera.Sniffing.TeraSniffer.HandleMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 152
   at Tera.Sniffing.MessageSplitter.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 53
   at Tera.Sniffing.MessageSplitter.ClientBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 41
   at Tera.PacketLog.BlockSplitter.OnBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 22
   at Tera.PacketLog.BlockSplitter.PopAllBlocks() in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 66
   at Tera.Sniffing.TeraSniffer.HandleClientToServerDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 164
   at Tera.Sniffing.ConnectionDecrypter.OnClientToServerDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 31
   at Tera.Sniffing.ConnectionDecrypter.ClientToServer(Byte[] data, Int32 needToSkip) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 107
   at Tera.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 143
   at NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 36
   at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 44
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpSniffer.cs:line 61
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSniffer.cs:line 16
   at NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:line 116
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 262
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDevice.cs:line 205
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 360
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread() in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:line 355
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2017-03-03 16:43:12,180 [1] INFO  CasualMeter.App - Checking for updates.
2017-03-03 16:43:12,406 [1] INFO  CasualMeter.App - Current Version: v1.2.3.4
2017-03-03 16:43:13,017 [1] INFO  CasualMeter.App - Starting up.
2017-03-03 16:43:13,619 [14] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
2017-03-03 16:44:00,176 [16] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Connected to server Tempest Reach.
2017-03-03 16:44:00,241 [16] ERROR CasualMeter.App - System.IO.FileNotFoundException: Could not find file 'C:\Users\Alex\AppData\Local\CasualMeter\app-1.2.3.4\res\opcodes\311380.txt'.
File name: 'C:\Users\Alex\AppData\Local\CasualMeter\app-1.2.3.4\res\opcodes\311380.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:line 37
   at Tera.Game.OpCodeNamer..ctor(String filename) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:line 23
   at CasualMeter.ShellViewModel.HandleMessageReceived(Message obj) in D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellViewModel.cs:line 443
   at Tera.Sniffing.TeraSniffer.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 80
   at Tera.Sniffing.TeraSniffer.HandleMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 152
   at Tera.Sniffing.MessageSplitter.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 53
   at Tera.Sniffing.MessageSplitter.ClientBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 41
   at Tera.PacketLog.BlockSplitter.OnBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 22
   at Tera.PacketLog.BlockSplitter.PopAllBlocks() in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 66
   at Tera.Sniffing.TeraSniffer.HandleClientToServerDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 164
   at Tera.Sniffing.ConnectionDecrypter.OnClientToServerDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 31
   at Tera.Sniffing.ConnectionDecrypter.ClientToServer(Byte[] data, Int32 needToSkip) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 107
   at Tera.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 143
   at NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 36
   at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 44
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpSniffer.cs:line 61
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSniffer.cs:line 16
   at NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:line 116
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 262
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDevice.cs:line 205
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 360
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread() in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:line 355
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2017-03-03 16:47:22,447 [1] INFO  CasualMeter.App - Checking for updates.
2017-03-03 16:47:22,677 [1] INFO  CasualMeter.App - Current Version: v1.2.3.4
2017-03-03 16:47:23,319 [1] INFO  CasualMeter.App - Starting up.
2017-03-03 16:47:24,009 [16] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
2017-03-03 16:47:36,639 [1] ERROR CasualMeter.App - System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at CasualMeter.ShellView.ExportsDir_OnClick(Object sender, RoutedEventArgs e) in D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellView.xaml.cs:line 221
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Alexotic** [comment]
not sure how to go about fixing this
