### ISSUE TITLE
Not connecting to server

### ISSUE THREAD

**Issue by DestinedAzn** [lunyx/CasualMeter#139]
I installed winpcap, reinstalled, restarted, added firewall exception, and the meter still won't show my server when I log into it. The only error that shows up on my log is

`2017-03-04 17:39:05,698 [1] ERROR CasualMeter.App - System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at CasualMeter.ShellView.ExportsDir_OnClick(Object sender, RoutedEventArgs e) in D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellView.xaml.cs:line 221
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

other than that, its just opening and closing the meter

**Comment by Gl0** [comment]
Try [npcap](https://nmap.org/npcap/) (check support winpcap api in installer), it works on much more network connection types then outdated winpcap. 
If that doesn't help - 
1.check "use raw sockets" in settings menu, 
2.recheck that firewall rule don't have any macro like %appdata% in path and points to correct exe, 
3.run meter as admin.

**Comment by DestinedAzn** [comment]
it still isn't working after doing all the things you've said to do and the log file doesn't show anything either

`2017-03-04 19:07:39,423 [1] INFO  CasualMeter.App - Starting up.
2017-03-04 19:11:10,129 [1] INFO  CasualMeter.App - Closing.
2017-03-04 19:11:43,579 [1] INFO  CasualMeter.App - Checking for updates.
2017-03-04 19:11:43,968 [1] INFO  CasualMeter.App - Current Version: v1.2.3.6
2017-03-04 19:11:44,896 [1] INFO  CasualMeter.App - Starting up.
2017-03-04 19:11:51,352 [14] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
2017-03-04 19:11:51,353 [15] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been disabled.`

**Comment by DestinedAzn** [comment]
It seemed to have fixed it self over time- closing this thread
