### ISSUE TITLE
keep saying unexpected error

### ISSUE THREAD

**Issue by NEON714** [lunyx/CasualMeter#145]
here is the log

`2017-04-27 13:45:14,267 [1] INFO  CasualMeter.App - Checking for updates.
2017-04-27 13:45:15,431 [1] INFO  CasualMeter.App - Current Version: v1.2.4.5
2017-04-27 13:45:16,687 [1] INFO  CasualMeter.App - Starting up.
2017-04-27 13:45:17,373 [11] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
2017-04-27 13:46:52,655 [13] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Connected to server Celestial Hills.
2017-04-27 13:51:52,505 [1] INFO  CasualMeter.App - Closing.
2017-04-27 13:51:53,992 [1] INFO  CasualMeter.App - Checking for updates.
2017-04-27 13:51:54,999 [1] INFO  CasualMeter.App - Current Version: v1.2.4.5
2017-04-27 13:51:56,284 [1] INFO  CasualMeter.App - Starting up.
2017-04-27 13:51:57,031 [11] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
2017-04-27 13:52:56,698 [13] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Connected to server Celestial Hills.
2017-04-27 13:55:05,359 [13] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Logged in to server Celestial Hills.
2017-04-27 13:55:05,730 [13] ERROR CasualMeter.App - System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Tera.Game.HotDotDatabase..ctor(String folder, String language) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\HotDotDatabase.cs:line 62
   at Tera.Data.TeraData..ctor(BasicTeraData basicData, String region, Boolean detectBosses) in D:\Workspace\visualstudio\CasualMeter\Tera.Data\TeraData.cs:line 22
   at Tera.Data.BasicTeraData.<>c__DisplayClass18_0.<.ctor>b__0(String region) in D:\Workspace\visualstudio\CasualMeter\Tera.Data\BasicTeraData.cs:line 35
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Tera.Game.Helpers.<>c__DisplayClass0_0`2.<Memoize>b__0(T x) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\Helpers.cs:line 15
   at Tera.Data.BasicTeraData.DataForRegion(String region) in D:\Workspace\visualstudio\CasualMeter\Tera.Data\BasicTeraData.cs:line 26
   at CasualMeter.ShellViewModel.HandleMessageReceived(Message obj) in D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellViewModel.cs:line 432
   at Tera.Sniffing.TeraSniffer.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 80
   at Tera.Sniffing.TeraSniffer.HandleMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 152
   at Tera.Sniffing.MessageSplitter.OnMessageReceived(Message message) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 53
   at Tera.Sniffing.MessageSplitter.ServerBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:line 46
   at Tera.PacketLog.BlockSplitter.OnBlockFinished(Byte[] block) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 22
   at Tera.PacketLog.BlockSplitter.PopAllBlocks() in D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:line 66
   at Tera.Sniffing.TeraSniffer.HandleServerToClientDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 158
   at Tera.Sniffing.ConnectionDecrypter.OnServerToClientDecrypted(Byte[] data) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 37
   at Tera.Sniffing.ConnectionDecrypter.ServerToClient(Byte[] data, Int32 needToSkip) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:line 127
   at Tera.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 145
   at NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 36
   at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:line 44
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpSniffer.cs:line 61
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSniffer.cs:line 16
   at NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:line 116
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 262
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDevice.cs:line 205
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 360
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread() in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:line 355
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2017-04-27 13:56:07,082 [1] INFO  CasualMeter.App - Checking for updates.
2017-04-27 13:56:08,327 [1] INFO  CasualMeter.App - Current Version: v1.2.4.5
2017-04-27 13:56:09,641 [1] INFO  CasualMeter.App - Starting up.
2017-04-27 13:56:11,063 [11] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
`

**Comment by NEON714** [comment]
nvm, i dont know why but when i delete the log file, i got no more error

**Comment by neverdiw** [comment]
Same error here.

**Comment by Gl0** [comment]
Seems @lunyx published old version of tera.core.dll

**Comment by Gl0** [comment]
[tera.core.zip](https://github.com/lunyx/CasualMeter/files/961534/tera.core.zip)
You can workaround this issue by replacing it. Or wait for updated release.

**Comment by lunatiqgodx** [comment]
GI0 thank you, replacing those files in the casualmeter directory fixed the issue. you are a true hero! @lunyx buy this man lunch or smtn.

**Comment by lunyx** [comment]
That's strange, I'm fairly sure it was the updated version.  In any case, I just released it again and it's working for me.  Can someone confirm?

**Comment by Gl0** [comment]
At least now it has updated code inside.

**Comment by lunatiqgodx** [comment]
So no lunch then? :P

**Comment by lunyx** [comment]
I provide him with licenses to productivity tools so that he can work even harder.
