### ISSUE TITLE
meter stops working randomly

### ISSUE THREAD

**Issue by MassDeception** [lunyx/CasualMeter#153]
Having some issues with the meter heres the logs : 
2017-08-02 04:40:02,373 [1] INFO  CasualMeter.App - Checking for updates.
2017-08-02 04:41:43,461 [1] INFO  CasualMeter.App - Current Version: v1.2.4.7
2017-08-02 04:41:43,662 [1] INFO  CasualMeter.App - Starting up.
2017-08-02 04:41:44,429 [3] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
2017-08-02 04:43:21,245 [16] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Connected to server Mount Tyrannas.
2017-08-02 04:44:09,281 [16] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Logged in to server Mount Tyrannas.
2017-08-02 05:38:49,723 [16] ERROR CasualMeter.App - System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.ArraySegment`1..ctor(T[] array, Int32 offset, Int32 count)
   at NetworkSniffer.Packets.Ip4Packet.get_Payload() in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\Packets\IpPacket.cs:line 37
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpSniffer.cs:line 64
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSniffer.cs:line 16
   at NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:line 116
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 262
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDevice.cs:line 205
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 360
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread() in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:line 355
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2017-08-02 14:08:48,923 [1] INFO  CasualMeter.App - Checking for updates.
2017-08-02 14:08:51,183 [1] INFO  CasualMeter.App - Current Version: v1.2.4.7
2017-08-02 14:08:51,641 [1] INFO  CasualMeter.App - Starting up.
2017-08-02 14:08:54,847 [13] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
2017-08-02 14:10:53,239 [14] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Connected to server Mount Tyrannas.
2017-08-02 14:11:20,225 [14] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Logged in to server Mount Tyrannas.
2017-08-02 14:27:13,899 [1] INFO  CasualMeter.App - Closing.
2017-08-02 14:27:20,235 [1] INFO  CasualMeter.App - Checking for updates.
2017-08-02 14:27:21,875 [1] INFO  CasualMeter.App - Current Version: v1.2.4.7
2017-08-02 14:27:22,304 [1] INFO  CasualMeter.App - Starting up.
2017-08-02 14:27:24,396 [12] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Sniffer has been enabled.
2017-08-02 14:27:52,035 [13] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Connected to server Mount Tyrannas.
2017-08-02 14:27:58,237 [13] INFO  CasualMeter.ViewModels.Base.CasualViewModelBase - Logged in to server Mount Tyrannas.
2017-08-02 14:30:25,357 [13] ERROR CasualMeter.App - System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.ArraySegment`1..ctor(T[] array, Int32 offset, Int32 count)
   at NetworkSniffer.Packets.Ip4Packet.get_Payload() in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\Packets\IpPacket.cs:line 37
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpSniffer.cs:line 64
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSniffer.cs:line 16
   at NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:line 116
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 262
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDevice.cs:line 205
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:line 360
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread() in d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:line 355
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Gl0** [comment]
Meter receives corrupted packet from winpcap and. That's may be hardware or driver issue. Try updating your network card drivers and switching to latest npcap.
