### ISSUE TITLE
Application cannot be started. Contact the application vendor

### ISSUE THREAD

**Issue by d3th4** [lunyx/CasualMeter#23]
PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.34209
	System.Deployment.dll 		: 4.0.30319.34280 built by: FX452RTMGDR
	clr.dll 			: 4.0.30319.34209 built by: FX452RTMGDR
	dfdll.dll 			: 4.0.30319.34280 built by: FX452RTMGDR
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: file:///C:/Users/bjk/Downloads/CasualMeter%20(1).application
	Deployment Provider url		: http://casualmeter.azurewebsites.net/install/CasualMeter.application
						Server		: Microsoft-IIS/8.0
						X-Powered-By	: ASP.NET
	Application url			: http://casualmeter.azurewebsites.net/install/Application%20Files/CasualMeter_1_0_5_2/CasualMeter.exe.manifest
						Server		: Microsoft-IIS/8.0
						X-Powered-By	: ASP.NET

IDENTITIES
	Deployment Identity		: CasualMeter.application, Version=1.0.5.2, Culture=neutral, PublicKeyToken=20d6e3ba73542d2e, processorArchitecture=msil
	Application Identity		: CasualMeter.exe, Version=1.0.5.2, Culture=neutral, PublicKeyToken=20d6e3ba73542d2e, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\bjk\Downloads\CasualMeter (1).application resulted in exception. Following failure messages were detected:
		+ The application binding data format is invalid. (Exception from HRESULT: 0x800736B2)

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [22/11/2015 4:51:55 PM] : Activation of C:\Users\bjk\Downloads\CasualMeter (1).application has started.
	* [22/11/2015 4:51:56 PM] : Processing of deployment manifest has successfully completed.
	* [22/11/2015 4:51:56 PM] : Installation of the application has started.
	* [22/11/2015 4:52:02 PM] : Processing of application manifest has successfully completed.
	* [22/11/2015 4:52:02 PM] : Found compatible runtime version 4.0.30319.
	* [22/11/2015 4:52:02 PM] : Request of trust and detection of platform is complete.
	* [22/11/2015 4:52:57 PM] : Downloading of subscription dependencies is complete.
	* [22/11/2015 4:52:57 PM] : Commit of the downloaded application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [22/11/2015 4:52:57 PM] System.Runtime.InteropServices.COMException
		- The application binding data format is invalid. (Exception from HRESULT: 0x800736B2)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IEnumSTORE_ASSEMBLY.Next(UInt32 celt, STORE_ASSEMBLY[] rgelt)
			at System.Deployment.Internal.Isolation.StoreAssemblyEnumeration.MoveNext()
			at System.Deployment.Application.ComponentStore.CollectCrossGroupApplications(Uri codebaseUri, DefinitionIdentity deploymentIdentity, Boolean& identityGroupFound, Boolean& locationGroupFound, String& identityGroupProductName)
			at System.Deployment.Application.SubscriptionStore.CommitApplication(SubscriptionState& subState, CommitApplicationParams commitParams)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by lunyx** [comment]
https://social.msdn.microsoft.com/Forums/en-US/637f2923-91a4-400c-830e-2d92c4e908ed/the-application-binding-data-format-is-invalid
