### ISSUE TITLE
Meter not showing up but in system tray

### ISSUE THREAD

**Issue by whittu** [lunyx/CasualMeter#28]
My meter was working a couple days ago but suddenly it stopped working. I have it open (process is still open) but nothing pops up even with tera opened. The meter icon is still in the system tray and I can't even exit it unless I close it manually through the task manager. I disabled my anti virus so idk what's causing the issue. 

my logs:

2015-11-29 17:23:23,668 [1] INFO  CasualMeter.App - Starting up.
2015-11-29 17:23:23,995 [1] ERROR CasualMeter.App - System.NullReferenceException: Object reference not set to an instance of an object.
   at CasualMeter.Common.Helpers.HotkeyHelper.Deactivate()
   at CasualMeter.Common.Helpers.ProcessHelper.UpdateHotKeys()
   at CasualMeter.ShellView.OnInitialized(EventArgs e)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at System.Windows.FrameworkElement.EndInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   at System.Xaml.XamlObjectWriter.Logic_EndInit(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteEndObject()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at CasualMeter.ShellView.InitializeComponent()
   at CasualMeter.ShellView..ctor()

EDIT: I have also reinstalled WINPCAP but no luck

**Comment by lunyx** [comment]
Have you tried reopening it and making sure it's on the latest version?
