### ISSUE TITLE
app download did not succeed

### ISSUE THREAD

**Issue by xrzrx** [lunyx/CasualMeter#30]
One day the meter just stopped working. After uninstall, I cant reinstall.  2 different errors so far

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://casualmeter.azurewebsites.net/install/CasualMeter.application resulted in exception. Following failure messages were detected:
		+ Downloading http://casualmeter.azurewebsites.net/install/Application Files/CasualMeter_1_0_5_7/CasualMeter.exe.deploy did not succeed.
		+ The underlying connection was closed: The connection was closed unexpectedly.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [12/2/2015 3:07:24 PM] : Activation of http://casualmeter.azurewebsites.net/install/CasualMeter.application has started.
	* [12/2/2015 3:07:24 PM] : Processing of deployment manifest has successfully completed.
	* [12/2/2015 3:07:24 PM] : Installation of the application has started.
	* [12/2/2015 3:07:24 PM] : Processing of application manifest has successfully completed.
	* [12/2/2015 3:07:26 PM] : Found compatible runtime version 4.0.30319.
	* [12/2/2015 3:07:26 PM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [12/2/2015 3:07:36 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://casualmeter.azurewebsites.net/install/Application Files/CasualMeter_1_0_5_7/CasualMeter.exe.deploy did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The underlying connection was closed: The connection was closed unexpectedly.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

and 

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://casualmeter.azurewebsites.net/install/CasualMeter.application resulted in exception. Following failure messages were detected:
		+ File, CasualMeter.exe, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [11/30/2015 3:14:38 PM] : Activation of http://casualmeter.azurewebsites.net/install/CasualMeter.application has started.
	* [11/30/2015 3:14:38 PM] : Processing of deployment manifest has successfully completed.
	* [11/30/2015 3:14:38 PM] : Installation of the application has started.
	* [11/30/2015 3:14:39 PM] : Processing of application manifest has successfully completed.
	* [11/30/2015 3:14:40 PM] : Found compatible runtime version 4.0.30319.
	* [11/30/2015 3:14:40 PM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [11/30/2015 3:15:02 PM] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, CasualMeter.exe, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by lunyx** [comment]
If you have antivirus, try disabling it.  It might be deleting files.

**Comment by xrzrx** [comment]
Turned off malware bytes and re-downloaded still same error

**Comment by Liombe** [comment]
Thank you very much, it worked for me.

**Comment by lunyx** [comment]
Use the new download link on the main page and try again.
