### ISSUE TITLE
Meter crashes after starting Tera

### ISSUE THREAD

**Issue by Blcksphr** [lunyx/CasualMeter#90]
Hellu,

I've got this problem with your meter. Whenever I start Tera the DPS Meter Crashes.

Info from log:
2016-05-28 10:38:43,654 [1] INFO  CasualMeter.App - Checking for updates.
2016-05-28 10:38:43,669 [1] INFO  CasualMeter.App - Current Version: v1.2.0.2
2016-05-28 10:38:45,163 [1] INFO  CasualMeter.App - Starting up.
2016-05-28 10:38:45,924 [14] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been enabled.
2016-05-28 10:38:52,111 [1] INFO  CasualMeter.App - Closing.
2016-05-28 12:56:54,057 [1] INFO  CasualMeter.App - Checking for updates.
2016-05-28 12:56:54,071 [1] INFO  CasualMeter.App - Current Version: v1.2.0.2
2016-05-28 12:56:54,599 [1] INFO  CasualMeter.App - Starting up.
2016-05-28 12:56:54,955 [13] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been enabled.
2016-05-28 12:58:24,833 [14] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Connected to server Killian.
2016-05-28 12:59:34,496 [14] ERROR CasualMeter.App - System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.MemoryStream.InternalReadInt32()
   at System.IO.BinaryReader.ReadInt32()
   at Tera.Game.Messages.SAddCharmStatus..ctor(TeraMessageReader reader) in D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Messages\Server\S_ADD_CHARM_STATUS.cs:line 12

**Comment by Gl0** [comment]
@lunyx haven't update compiled version to last EU patch yet. You can download fresh db manually from https://github.com/neowutran/TeraDpsMeterData

**Comment by lunyx** [comment]
Released just now.

**Comment by Blcksphr** [comment]
Hey again,

after update everything is working perfectly.

Thank you for fast reply and keep up the good work!
