### ISSUE TITLE
Casualmeter Crashes right after opening it

### ISSUE THREAD

**Issue by chimney31** [lunyx/CasualMeter#93]
2016-06-05 23:09:32,159 [1] ERROR CasualMeter.App - System.NullReferenceException: Object reference not set to an instance of an object.
   at CasualMeter.Common.Helpers.SettingsHelper..ctor() in D:\Workspace\visualstudio\CasualMeter\CasualMeter.Common\Helpers\SettingsHelper.cs:line 40
   at CasualMeter.Common.Helpers.SettingsHelper.<>c.<.cctor>b__21_0() in D:\Workspace\visualstudio\CasualMeter\CasualMeter.Common\Helpers\SettingsHelper.cs:line 17
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at CasualMeter.Common.Helpers.HotkeyHelper.Deactivate() in D:\Workspace\visualstudio\CasualMeter\CasualMeter.Common\Helpers\HotkeyHelper.cs:line 56
   at CasualMeter.Common.Helpers.ProcessHelper.UpdateHotKeys() in D:\Workspace\visualstudio\CasualMeter\CasualMeter.Common\Helpers\ProcessHelper.cs:line 42
   at CasualMeter.Common.Helpers.ProcessHelper.OnFocusedWindowChanged(IntPtr hWinEventHook, UInt32 eventType, IntPtr hwnd, Int32 idObject, Int32 idChild, UInt32 dwEventThread, UInt32 dwmsEventTime) in D:\Workspace\visualstudio\CasualMeter\CasualMeter.Common\Helpers\ProcessHelper.cs:line 47

Help!

My app crashes by itself right after opening it. I tried turning malwarebytes, windows defender, smartscreen and firewall off but same issue. Its been like this for 2 months and i tried fixing myself before bothering you, searched for similar issues but didnt find any.

Windows 10 Home . Exe files and desktop shortcuts were ran as admin.

 I appreciate any help! thanks.

**Comment by Gl0** [comment]
Try to delete %appdata%\CasualMeter\settings.json

**Comment by chimney31** [comment]
Thanks Gi0 your suggestion worked! CM working perfectly now.
